version: '2'
catalog:
  name: "Cachet"
  version: "v2.3.13-rancher1"
  description: "An open source status page for everyone"
  minimum_rancher_version: v0.51.0
  questions:
    - variable: public_port
      description: "public port to access Cachet web"
      label: "Public Port"
      required: true
      default: "80"
      type: "int" 
    - variable: db_password
      description: "Database password"
      label: "Database password"
      default: "changeme"
      type: "password"
    - variable: debug
      description: "Enable debug"
      label: "Debug"
      type: "boolean"
      default: "false"
    - variable: volume_driver
      description: "Volume driver to use with this service"
      label: "Volume driver"
      required: true
      default: "local"
      type: enum
      options:
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
